<footer>
            <section class="footer">
                <ul class="footer-nav">
                    <li>
                        <a href="index.php" class="footer-logo"><img src="styles/images/logo.png"
                                alt="VITACODER Logo"></a>
                        <p>&copy; 2024 <a href="index.php">VitaCoder</a>. All rights reserved.</p>
                    </li>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="jobs.php">Find jobs</a></li>
                    <li><a href="about.php">About Us</a></li>
                    <li><a href="https://youtu.be/JUnbEPEMIkQ">Video Link 1</a></li>
                    <li><a href="">Video Link 2</a></li>
                </ul>
                <li class="contact-footer">Contact Us:
                    <ul>
                        <li><a href="mailto:104828510@student.swin.edu.au">Uyen</a></li>
                        <li><a href="mailto:105338010@student.swin.edu.au">Michael</a></li>
                        <li><a href="mailto:105034253@student.swin.edu.au">James</a></li>
                    </ul>
                </li>
                </ul>
            </section>
</footer>