<header class="header">
    <a href="index.php" class="header-logo">
        <img src="styles/images/logo.png" alt="VITACODER Logo">
    </a>
    <input type="checkbox" id="hbg" title="hamburger menu">
    <label class="hbg" for="hbg" title="hamburger menu">
        <span> </span>
        <span>. </span>
        <span> </span>
    </label>
    <ul class="header123">
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="manage.php">Manage</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">HTML Enhancements</a></li>
        <li><a href="phpenhancements.php">PHP Enhancements</a></li>
        <li class="contact">
            <a href="#">Contact</a>
            <ul class="mailto">
                <li><a href="mailto:104828510@student.swin.edu.au">Uyen</a></li>
                <li><a href="mailto:105338010@student.swin.edu.au">Michael</a></li>
                <li><a href="mailto:105034253@student.swin.edu.au">James</a></li>
            </ul>
        </li>
    </ul>
</header>
